cosmetic fixups to bash code in rpm spec file (mostly indentation)

diff --git a/packaging/rpm/qpsmtpd.spec.in b/packaging/rpm/qpsmtpd.spec.in
--- a/packaging/rpm/qpsmtpd.spec.in
+++ b/packaging/rpm/qpsmtpd.spec.in
@@ -65,16 +65,14 @@ rm -rf $RPM_BUILD_ROOT
 rm -rf $RPM_BUILD_ROOT
 eval `perl '-V:installarchlib'`
 mkdir -p $RPM_BUILD_ROOT/$installarchlib
-if grep -q DESTDIR Makefile
-then
-        make DESTDIR=$RPM_BUILD_ROOT
-        find blib/lib -name '*.pm.*' -exec rm -f {} \;
-        make DESTDIR=$RPM_BUILD_ROOT install
-
+if grep -q DESTDIR Makefile ; then
+  make DESTDIR=$RPM_BUILD_ROOT
+  find blib/lib -name '*.pm.*' -exec rm -f {} \;
+  make DESTDIR=$RPM_BUILD_ROOT install
 else
-        make PREFIX=$RPM_BUILD_ROOT/usr
-        find blib/lib -name '*.pm.*' -exec rm -f {} \;
-        make PREFIX=$RPM_BUILD_ROOT/usr install
+  make PREFIX=$RPM_BUILD_ROOT/usr
+  find blib/lib -name '*.pm.*' -exec rm -f {} \;
+  make PREFIX=$RPM_BUILD_ROOT/usr install
 fi
 mkdir -p ${RPM_BUILD_ROOT}%{_datadir}/%{name}
 rm -f ${RPM_BUILD_ROOT}%{_datadir}/%{name}/plugins/*.*
@@ -103,17 +101,17 @@ cp %{SOURCE6} $RPM_BUILD_ROOT%{_docdir}/%{name}-apache-%{version}
 
 find ${RPM_BUILD_ROOT}%{_prefix} \( -name perllocal.pod -o -name .packlist \) -exec rm {} \;
 find ${RPM_BUILD_ROOT}%{_prefix} -type f -print | \
-        sed "s@^$RPM_BUILD_ROOT@@g"     | \
-        grep -v [Aa]sync                | \
-        grep -v packaging               | \
-        grep -v README.selinux          | \
-        grep -v in\\.qpsmtpd            | \
-        grep -v /Apache                 | \
-        grep -v /Danga                  | \
-        grep -v Qpsmtpd/PollServer.pm   > %{name}-%{version}-%{release}-filelist
+  sed "s@^$RPM_BUILD_ROOT@@g"     | \
+  grep -v [Aa]sync                | \
+  grep -v packaging               | \
+  grep -v README.selinux          | \
+  grep -v in\\.qpsmtpd            | \
+  grep -v /Apache                 | \
+  grep -v /Danga                  | \
+  grep -v Qpsmtpd/PollServer.pm   > %{name}-%{version}-%{release}-filelist
 if [ "$(cat %{name}-%{version}-%{release}-filelist)X" = "X" ] ; then
-    echo "ERROR: EMPTY FILE LIST"
-    exit -1
+  echo "ERROR: EMPTY FILE LIST"
+  exit -1
 fi
 
 find ${RPM_BUILD_ROOT}%{_prefix} -type f -print | \
@@ -124,8 +122,8 @@ find ${RPM_BUILD_ROOT}%{_prefix} -type f -print | \
 	grep -v /Danga                  | \
 	grep -v Qpsmtpd/PollServer.pm   | cat - %{name}-%{version}-%{release}-filelist | sort | uniq -u > %{name}-%{version}-%{release}-apache-filelist
 if [ "$(cat %{name}-%{version}-%{release}-apache-filelist)X" = "X" ] ; then
-    echo "ERROR: EMPTY FILE LIST"
-    exit -1
+  echo "ERROR: EMPTY FILE LIST"
+  exit -1
 fi
 
 %files -f %{name}-%{version}-%{release}-filelist
@@ -148,16 +146,14 @@ fi
 %{_sbindir}/in.qpsmtpd
 
 %pre
-if ! id smtpd >/dev/null 2>&1
-then
-    # need to create smtpd user.
-    if perl -e 'exit ! defined(getgrnam("postdrop"))'
-    then
-        # if postfix is installed, we will probably use
-        # queue/postfix, which will need this:
-        supp="-G postdrop"
-    fi
-    useradd -r -M -s /bin/false $supp smtpd
+if ! id smtpd >/dev/null 2>&1 ; then
+  # need to create smtpd user.
+  if perl -e 'exit ! defined(getgrnam("postdrop"))' ; then
+     # if postfix is installed, we will probably use
+     # queue/postfix, which will need this:
+     supp="-G postdrop"
+  fi
+  useradd -r -M -s /bin/false $supp smtpd
 fi
 
 %changelog
